Change in package name
globalgov/manytrade pull request #18
Opened 2021-11-26 11:03 UTC by jaeltan

# Description
Minor changes to package including change of name from qTrade to manytrade.

## Package
* Closed #16 by changing package name from qTrade to manytrade
* Closed #10 by updating wording in ReadME files and added new logo with new name

# Checklist:

- [X] PR form
  - [X] I have given this pull request an informative title
  - [X] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [X] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [X] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [X] Documentation
  - [X] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [X] Any longer functions are commented inline so that it is easier to debug in the future
  - [X] PR description above and the NEWS.md file are aligned
  - [X] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2021-11-29 08:55 UTC, henriquesposito requested changes
Great job @jaeltan ! I have requested a few more changes before we are ready to go. Please do not hesitate to ask if you have any questions about the comments! Thank you

2021-11-29 08:55 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> +          remotes::install_github("globalgov/manydata")
This is not a dependency anymore, remove

2021-11-29 08:55 UTC, henriquesposito commented on DESCRIPTION
> +Description: Package manytrade provides an ensemble of data on international trade agreements,
The manytrade package

2021-11-29 08:55 UTC, henriquesposito commented on NEWS.md
> +## Functions
Is this in the package? If so, do we need it?

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-references.R
> +#' please use the `data_source()`, `data_contrast()`, and `data_evolution()`
Remove data_evolution() here, we do not currently have the function

2021-11-29 08:55 UTC, henriquesposito commented on README.Rmd
> +Simply install the core package, [manydata](https://github.com/globalgov/manydata), as follows,
Remove "as follows" ... weird wording

2021-11-29 08:55 UTC, henriquesposito commented on README.Rmd
> +manytrade is a data package in the [many packages](https://github.com/globalgov/manydata) universe.
Link should be to organization maybe? (i.e. https://github.com/globalgov)

2021-11-29 08:55 UTC, henriquesposito commented on README.Rmd
> +The [many packages](https://github.com/globalgov/manydata) universe is aimed at collecting, connecting and correcting network data across issue-domains of global governance.
link to organization?

2021-11-29 08:55 UTC, henriquesposito commented on README.Rmd
> +[manydata](https://github.com/globalgov/manydata) includes a number of
manypkgs?

2021-11-29 08:55 UTC, henriquesposito commented on data-raw/references/DESTA_REF/DESTA_REF.bib
> +	title = {The {Design} of {International} {Trade} {Agreements}: {Introducing} a {New} {Database}},
Just a question: why the {} everywhere?

2021-11-29 08:55 UTC, henriquesposito commented on data-raw/references/DESTA_REF/prepare-DESTA_REF.R
> +destaid<- qTrade::agreements$DESTA %>%
manytrade

2021-11-29 08:55 UTC, henriquesposito commented on docs/sitemap.xml
> +    <loc>https://globalgov.github.io/qTrade//reference/code_countryname.html</loc>
manytrade

2021-11-29 08:55 UTC, henriquesposito commented on docs/sitemap.xml
> +    <loc>https://globalgov.github.io/qTrade//reference/references.html</loc>
manytrade

2021-11-29 08:55 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
>       - agreements
you can add the references database here as well

2021-11-29 08:55 UTC, henriquesposito commented on tests/testthat/test_DESTA_REF.R
> +# Test if  meets the q ecosystem requirements
the many packages universe

2021-11-29 08:55 UTC, henriquesposito commented on tests/testthat/test_GPTAD.R
> +# Test if  meets the many packages ecosystem requirements
the many packages universe

2021-11-29 08:55 UTC, henriquesposito commented on tests/testthat/test_DESTA_REF.R
> +# Test if  meets the q ecosystem requirements
Could you please change this in the other test scripts as well? Thank you!

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-references.R
> +#' please use the `data_source()`, `data_contrast()`, and `data_evolution()`
Could you please also remove data_evolution() from all database documentation scripts? Thank you.

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-agreements.R
> +#' agreements database documentation
The datasets here have qID but no qID_ref? Should they not have both?

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-agreements.R
> +#' agreements database documentation
Remove data_evolution() below, we do not have the function... template has been updated already but this is the old template...

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-memberships.R
>  #' functions.
Remove data_evolution() above

2021-11-29 08:55 UTC, henriquesposito commented on R/qTrade-references.R
> +#' 3 variables: qID1, RefType, qID2.}
Did you generate these IDs from qID or qID_ref? qID_ref generated for the database are more accurate once you start adding more datasets here...

2021-11-29 10:19 UTC, jaeltan commented on NEWS.md
> +## Functions
I used the code_countryname function to wrangle the GPTAD membership data, it's in the R folder

2021-11-29 10:24 UTC, jaeltan commented on data-raw/references/DESTA_REF/DESTA_REF.bib
> +	title = {The {Design} of {International} {Trade} {Agreements}: {Introducing} a {New} {Database}},
I can't remember why but I think it was a formatting issue. I'll remove them.

2021-12-01 14:47 UTC, BBieri reviewed
Great work! Try to run `lintr::lint_dir()` on the package to lint the package to maintain a nice and pretty coding style.

2021-12-01 14:47 UTC, BBieri commented on data-raw/references/DESTA_REF/DESTA_REF.bib
> +}
Add a new line at the end of the file

2021-12-01 14:47 UTC, BBieri commented on data-raw/references/DESTA_REF/prepare-DESTA_REF.R
> +# First, it creates a set of tests for this object to ensure adherence
Remove duplicate paragraph

2021-12-01 14:47 UTC, BBieri commented on pkgdown/_pkgdown.yml
>          - text: qStates
Change to `manystates`

2021-12-02 09:00 UTC, henriquesposito requested changes
Great job @jaeltan with the changes and @BBieri with the review! Just a few more minor clarifications and changes and we should be ready to go! Thank you

2021-12-02 09:00 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> -      # install qData
This is not needed to render the README, the code chunk that refer to qData have been set to eval=FALSE until manydata is on CRAN. This is because of that old problem we have with this pushrelease.yml often not being able to download the package when merging a PR...

2021-12-02 09:00 UTC, henriquesposito commented on DESCRIPTION
> +Date: 2021-11-29
date

2021-12-02 09:00 UTC, henriquesposito commented on DESCRIPTION
> -    globalgov/qData
Only if the PR in manydata is closed first... Also, if dependency is not required for package to build and all the CMD checks pass, we can leave it later either as a suggested package.

2021-12-02 09:00 UTC, henriquesposito commented on NEWS.md
> +2021-12-01
date

2021-12-02 09:00 UTC, henriquesposito commented on NEWS.md
> +## Functions
I agree with Bernhard, if it is a general function we can either change or combine in another package. We also already have `manypkgs::code_parties()`by the way that does similar things... What I suggest @jaeltan is to open an issue for this so that we can address it at a later stage.

2021-12-02 09:00 UTC, henriquesposito commented on README.Rmd
> +functions that make it easy to create a new package in the `many packages` universe
many package

2021-12-02 09:02 UTC, jaeltan commented on NEWS.md
> +## Functions
@BBieri I think that is a good idea, we just need to copy the french names over from the countryregex list in manytrade so that it works for cleaning the data in manytrade too.

Sidenote: I saw `manystates::code_states()` is named 'Code Parties' in the R script - should we rename it to 'Code States' or something like that to avoid confusion with `manypkgs::code_parties()`?

2021-12-02 09:11 UTC, jaeltan commented on README.Rmd
> +functions that make it easy to create a new package in the `many packages` universe
Just to make sure: I will change this to 'create a many package in the `many` universe

2021-12-02 09:32 UTC, jaeltan commented on NEWS.md
> +## Functions
Issue #19 created! @henriquesposito @BBieri

2021-12-02 09:44 UTC, henriquesposito commented on NEWS.md
> +## Functions
@jaeltan Great catch, I just renamed the function in the documentation!

Thank you as well for opening the issue!

2021-12-03 08:42 UTC, henriquesposito approved these changes
Great job @jaeltan ! Just a few more very minor comments to address and then you can merge away! Thank you

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +Please also check out [`{manydata}`](https://github.com/globalgov/manydata) for more about the other packages in the many universe.
many packages universe maybe

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +manytrade is a data package in the [many](https://github.com/globalgov/) universe.
In manydata I refer to the many packages universe ... though, I do not think it matters much here so your choice

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +The [many](https://github.com/globalgov/) universe is aimed at collecting, connecting and correcting network data across issue-domains of global governance.
many packages universe maybe

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +The many universe endeavours to be as transparent as possible about where data
many packages universe maybe

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +this package, but could be useful within the wider many universe,
many packages universe maybe

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +functions that make it easy to create a new 'many package' in the many
create a new 'many package' and populate ... (remove the many universe)

2021-12-03 08:42 UTC, henriquesposito commented on README.Rmd
> +If you have any other ideas about how this package or the many universe more broadly
many packages universe maybe

2021-12-03 08:42 UTC, henriquesposito commented on data-raw/texts/AGR_TXT/AGR_TXT.bib
> +}
add new line at the end of script

2021-12-03 09:18 UTC, merged