Added ToTA and renamed variables in existing databases
globalgov/manytrade pull request #25
Opened 2022-03-14 10:39 UTC by jaeltan

# Description
Patch changes to package include renaming of variables in existing databases (`agreements` and `memberships`) and addition of `ToTA: Texts of Trade Agreements` to `texts` database.

## Package

* Closed #19 by merging `manytrade::code_countryname()` functionality into `manystates::code_states()`.
* Fixed #21 by redirecting reference to master branch to main branch in pushrelease workflow.
* Closed #14 by adding codecov, codefactor, lintr to package workflows and as badges.

## Data

* Fixed #23 by amending regex list stored in package and modifying `manystates::code_states()` to return original names if unmatched in regex list.
* Fixed #22 and #24 by renaming variables in databases.
  * Renamed "treaty_ID" and "many_ID" across all databases to "treatyID" and "manyID" respectively.
  * Renamed "L", "D", and "J" in the agreements database "DocType", "AgreementType", and "GeogArea" respectively.
  * Reformatted "Beg", "Signature", "Force" variables from YYYY format to YYYY-MM-DD format in `DESTA`, `TREND`, `LABPTA` datasets to be consistent across the `agreements` database.
* Closed #9 by adding `ToTA` to `texts` database.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-03-21 23:43 UTC, jhollway requested changes

2022-03-21 23:43 UTC, jhollway commented on .Rbuildignore
>  ^docs$
Maybe also add .DS_Store and .RDataTmp files to .Rbuildignore and .gitignore too?

2022-03-21 23:43 UTC, jhollway commented on .github/workflows/pushrelease.yml
> +          remotes::install_cran("covr")
No need to install covr if not calculating code coverage (lines 97-99)

2022-03-21 23:43 UTC, jhollway commented on README.Rmd
> +# manytrade <img src="man/figures/manytradeContainer.png" align="right"/>
Is this a large enough logo now?

2022-03-21 23:43 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    bootswatch: litera
Note that the logos are too small

2022-03-21 23:43 UTC, jhollway commented on shinyapp/trade_treaties_year/trade_mem.csv
> +"4","BTN-IND[NA]_1949O:BTN-IND[NA]_1949O","IND","Bhutan India","1949"
Why extra hard-coded data? Can't we use the data in the package?

2022-03-22 10:27 UTC, henriquesposito requested changes
@jaeltan Thank you very much for all the great work with changing variable names and finding out where the issues with the variables in database were! I suggested e few more changes, please let me know if you have any questions about the comments.

2022-03-22 10:27 UTC, henriquesposito commented on NEWS.md
> +# manytrade 0.1.1
This comment is for the PR title: could you please add a more informative title? Maybe something like: "Renamed variables in databases to give more informative names and removed unnecessary duplicates in databases"

2022-03-22 10:27 UTC, henriquesposito commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +# Extract useful columns from original GPTAD dataset and add treatyID column
Since the texts databases have been saved for later, should we save these preparation scripts for later as well? Just so that users might not be confused.

2022-03-22 10:27 UTC, henriquesposito commented on data-raw/texts/TOTA_TXT/TOTA_TXT.bib
> +@misc{alschner_2017,
Save it for later? @jaeltan I would suggest you open a new "texts" branch and move all the text related documents and data there for the time being.

2022-03-22 10:27 UTC, henriquesposito commented on data-raw/texts/TOTA_TXT/prepare-TOTA.R
> +# TEXTS OF TRADE AGREEMENTS (TOTA) Database Preparation Script
Save it for later? Or in another branch?

2022-03-23 08:49 UTC, henriquesposito approved these changes
Great job Jael! We are all good on my side to go. Please just make sure you double check that the pkgdown website builds properly for the package. Thank you!

2022-03-23 08:55 UTC, merged