Added GNEVAR dataset and added trade agreements texts
globalgov/manytrade pull request #28
Opened 2022-04-14 09:12 UTC by jaeltan

# Description

Added texts database to package and created GNEVAR dataset for trade agreements.  

## Data

* Added GNEVAR dataset for contributions to trade agreements datasets
  * Created consolidated version of trade agreements datasets using `manydata::consolidate()`
  * Added variables for membership conditions and membership procedures using `manypkgs::code_memberships()`
* Added `texts` database with trade agreements texts
  * Closed #9 by linking TOTA database to the `TOTA_TXT` dataset in the `texts` database.
  * Closed #17 by adding texts for trade agreements listed in the `agreements` database. To avoid overlaps, the texts are added to a combined `AGR_TXT` dataset in the `texts` database.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-05-05 09:04 UTC, henriquesposito requested changes
Great job @jaeltan , there is a lot of work here! I have requested a few changes and left a few other comments/questions. Please let me know if you have any questions. Thank you!

2022-05-05 09:09 UTC, jaeltan commented on data-raw/texts/TOTA_TXT/prepare-TOTA_TXT.R
> +# Due to the specificities of the TOTA database,
Do you mean combine the TOTA_TXT and AGR_TXT datasets in the text database?

2022-05-05 09:10 UTC, henriquesposito commented on DESCRIPTION
>      testthat (>= 3.0.0)
If the CMD checks are failing because of lazydata, you could try and add "LazyDataCompression:xz" in description file instead of "LazyData: true", it might work...

2022-05-05 09:12 UTC, jaeltan commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR <- manydata::favour(manytrade::agreements, "GPTAD") %>%
The GNEVAR dataset contains our contributions to the other datasets in the agreements database (for now it's the membership conditions and membership procedures variables), so I consolidated the agreements database to combine all the datasets while avoiding duplicate entries. But I see what your point here - should I move GNEVAR to a database on its own?

2022-05-05 09:12 UTC, henriquesposito commented on data-raw/texts/TOTA_TXT/prepare-TOTA_TXT.R
> +# Due to the specificities of the TOTA database,
Yes, this is what I mean. Could we not do this as we do it in manyenviron? We can just make sure that the source from the text is visible for users either with a link or a new variable (if already not available).

2022-05-05 09:16 UTC, henriquesposito commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR <- manydata::favour(manytrade::agreements, "GPTAD") %>%
I would say you should move and create a separate GNEVAR database/dataset. However, maybe @jhollway can better answer here. Thank you.

2022-05-05 09:16 UTC, jaeltan commented on data-raw/texts/TOTA_TXT/prepare-TOTA_TXT.R
> +# Due to the specificities of the TOTA database,
Ok I'll try. The only thing is that for TOTA I had to extract the titles and dates from the text itself so I'm not sure how much overlap there is between TOTA and the other datasets

2022-05-05 21:48 UTC, jhollway requested changes

2022-05-05 21:48 UTC, jhollway commented on DESCRIPTION
>  Package: manytrade
Note that `.DS_Store` should be in `.gitignore`

2022-05-05 21:48 UTC, jhollway commented on NEWS.md
> +2022-04-14
Update date?

2022-05-05 21:48 UTC, jhollway commented on NEWS.md
> +  * Created consolidated version of trade agreements datasets using `manydata::consolidate()`
I am also unclear about this: `manydata::consolidate()` is typically for (final) users and not developers.

2022-05-05 21:48 UTC, jhollway commented on NEWS.md
> +  * Closed #17 by adding texts for trade agreements listed in the `agreements` database. To avoid overlaps, the texts are added to a combined `AGR_TXT` dataset in the `texts` database.
This is not clear to me. Why are there texts appearing in two places?

2022-05-05 21:48 UTC, jhollway commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, AgreementType, DocType, GeogArea, Signature, Force, treatyID, destaID.}
line wrapping

2022-05-05 21:48 UTC, jhollway commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, AgreementType, DocType, GeogArea, Signature, Force, treatyID, gptadID.}
line length

2022-05-05 21:48 UTC, jhollway commented on R/manytrade-agreements.R
> +#' 16 variables: manyID, Title, Beg, Signature, Force, AgreementType, DocType, GeogArea, gptadID, destaID, trendID, treatyID, labptaID, totaID, Memb.conditions, Memb.procedures.}
line length

2022-05-05 21:48 UTC, jhollway commented on R/manytrade-texts.R
> +#' 9 variables: manyID, Title, Beg, Signature, Force, TreatyText, treatyID, url, totaID.}
line length

2022-05-05 21:48 UTC, jhollway commented on data-raw/agreements/GNEVAR/GNEVAR.bib
> +
What about citing e.g. TOTA?

2022-05-05 21:48 UTC, jhollway commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR <- manydata::favour(manytrade::agreements, "GPTAD") %>%
Yes, GNEVAR datasets are those observations that we have hand-coded/confirmed ourselves.

2022-05-05 21:48 UTC, jhollway commented on data-raw/texts/AGR_TXT/AGR_TXT.bib
> +
What does AGR stand for?

2022-05-05 21:48 UTC, jhollway commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +                        key = "manyID")
As above, why are we consolidating here?

2022-05-05 21:48 UTC, jhollway commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +links <- links[-314] # remove duplicate entry for New Zealand - Singapore
Numerical indexing could make this sensitive to database changes. If this has to be done here, can you use a search pattern like `grep()` to remove duplicates or use some programmatic way of identifying and removing duplicates?

2022-05-05 21:48 UTC, jhollway commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +  # scrap web pages
scrape?

2022-05-05 21:48 UTC, jhollway commented on tests/testthat/test_AGR_TXT.R
> +  pointblank::expect_col_exists(texts[["AGR_TXT"]], pointblank::vars(TreatyText))
line length

2022-05-05 21:48 UTC, jhollway commented on tests/testthat/test_DESTA.R
> +  pointblank::expect_col_exists(agreements[["DESTA"]], pointblank::vars(Signature))
line length

2022-05-05 21:48 UTC, jhollway commented on tests/testthat/test_DESTA_MEM.R
> +  pointblank::expect_col_exists(memberships[["DESTA_MEM"]], pointblank::vars(Beg))
line length

2022-05-05 21:48 UTC, jhollway commented on tests/testthat/test_GNEVAR.R
> +  pointblank::expect_col_exists(agreements[["GNEVAR"]], pointblank::vars(Signature))
line length

2022-05-09 06:51 UTC, jaeltan commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +                        key = "manyID")
There are a few overlaps between the datasets and we don't want duplicates in the list of agreements that we are web-scraping texts for. Consolidate is the easiest way to obtain a list of agreements from all datasets without duplicate entries. I think the same thing was done in manyenviron.

2022-05-09 06:53 UTC, jaeltan commented on data-raw/texts/AGR_TXT/AGR_TXT.bib
> +
I believe it stands for Agreements, this was what Esther named the texts dataset in manyenviron

2022-05-17 09:24 UTC, jaeltan commented on NEWS.md
> +  * Created consolidated version of trade agreements datasets using `manydata::consolidate()`
I've moved GNEVAR to a database and dataset on its own. Instead of using `manydata::consolidate()`, GNEVAR dataset now consists of all the datasets in the agreements database joined together.

2022-05-19 12:50 UTC, henriquesposito requested changes
Thank you Jael, great job! Just a few more comments and questions.

2022-05-19 12:50 UTC, henriquesposito commented on data-raw/texts/AGR_TXT/prepare-AGR_TXT.R
> +# Due to the specificities of the texts database,
Great, thank you Jael!

2022-05-19 12:50 UTC, henriquesposito commented on tests/testthat/test_DESTA_MEM.R
> +  pointblank::expect_col_exists(memberships[["DESTA_MEM"]],
Trailing whitespace

2022-05-19 12:50 UTC, henriquesposito commented on tests/testthat/test_DESTA_MEM.R
> +  pointblank::expect_col_exists(memberships[["DESTA_MEM"]],
Trailing whitespace

2022-05-19 12:50 UTC, henriquesposito commented on tests/testthat/test_TOTA.R
> +  pointblank::expect_col_exists(agreements[["TOTA"]],
Trailing whitespace

2022-05-25 06:17 UTC, jhollway commented on data-raw/gnevar/GNEVAR/prepare-GNEVAR.R
> +GNEVAR <- dplyr::bind_rows(manytrade::agreements$DESTA,
The idea behind the GNEVAR datasets are that they represent the data that we have personally collected/checked/coded. In the case of `{manyenviron}` it is a little complicated, because we've been working on it for many years and is quite intimately bound up with IEADB. Here it could be more independent?

2022-05-25 06:36 UTC, jhollway requested changes
Looks like a really good job on the trade texts @jaeltan, I look forward to investigating them more.

In the meantime, the big change necessary relates to @henriquesposito 's comments on where the `GNEVAR` dataset should be placed.

Please note also that there are still several `.DS_Store` files, which are not needed in such a repository. Please delete in addition to ignoring them from .git and .RBuild.

2022-05-25 06:36 UTC, jhollway commented on .gitignore
> +*.DS_Store
There's still a `.DS_Store` file in the repo root that seems to be already committed. You'll need to delete it.

2022-05-25 06:36 UTC, jhollway commented on NEWS.md
>  # manytrade 0.1.1
Remove extra lines.

2022-05-25 06:36 UTC, jhollway commented on NEWS.md
> +* Added `gnevar` database.
Is the dataset name small letters or capitals?

2022-05-25 06:36 UTC, jhollway commented on NEWS.md
> +  agreements texts, to GNEVAR dataset.
Do we want to advertise this a little more? After all, it was surely considerable work and also represents a significant advantage over existing datasets.

2022-05-25 06:36 UTC, jhollway commented on NEWS.md
> +  `texts` database and added metadata to `TOTA` dataset in `agreements` database.
Do we also want to advertise this a little more, since this is a significant offering too. For example, these offerings are not yet advertised in the README.

2022-05-25 06:36 UTC, jhollway commented on R/manytrade-agreements.R
>  #'
Remove empty lines

2022-05-25 06:36 UTC, jhollway commented on R/manytrade-gnevar.R
> +"gnevar"
But this shouldn't be it's own database -- gnevar should be a dataset within the agreements database, no?

2022-05-25 06:36 UTC, jhollway commented on R/manytrade-agreements.R
> +#' following 5 datasets: TREND, LABPTA, GPTAD, DESTA, TOTA.
Where is GNEVAR?

2022-05-25 06:36 UTC, jhollway commented on R/manytrade-texts.R
> +#'
Where are these empty lines coming from? Does the `{manypkgs}` template need updating?

2022-05-25 06:36 UTC, jhollway commented on data-raw/agreements/DESTA/prepare-DESTA.R
> +                        Force = messydates::make_messydate(as.character(entryforceyear))) %>%
Why is this `make_messydate()` and not `as_messydate()`?

2022-05-25 06:36 UTC, jhollway commented on data-raw/agreements/LABPTA/prepare-LABPTA.R
> +                        Force = messydates::make_messydate(as.character(year))) %>%
Why not `as_messydate()`?

2022-05-25 06:36 UTC, jhollway commented on data-raw/agreements/TOTA/TOTA.bib
> +  url          = {https://github.com/mappingtreaties/tota.git},
Isn't there another URL?

2022-05-25 18:54 UTC, henriquesposito commented
A bit more information on how to try and deal with these annoying ".DS_Store" files that keep on showing up https://github.com/2DegreesInvesting/resources/issues/115. Thank you!

2022-05-30 08:15 UTC, jaeltan commented on data-raw/agreements/DESTA/prepare-DESTA.R
> +                        Force = messydates::make_messydate(as.character(entryforceyear))) %>%
The error message generated from the previous function (`manypkgs::standardise_dates()`) prompted using make_messydate. Should it be as_messydate instead since it'snot creating a date from multiple variables? @henriquesposito

2022-05-30 08:58 UTC, jaeltan commented on data-raw/agreements/TOTA/TOTA.bib
> +  url          = {https://github.com/mappingtreaties/tota.git},
I added the UNCTAD url to the article

2022-05-30 21:25 UTC, jhollway commented on NEWS.md
>  * Added `GNEVAR` database.
Added it where/to what?

2022-05-31 11:56 UTC, henriquesposito approved these changes
Thank you for all the great work @jaeltan ! I will add a more informative defunct message for `standardise_dates()` that points users towards either `as_messydate()` or `make messydate()` depending on the case. Please feel free to change calls from `make_messydate()` to `as_messydate()` when single date variable is passed. Thank you!

2022-05-31 11:56 UTC, henriquesposito commented on data-raw/agreements/GPTAD/prepare-GPTAD.R
> +                     Force = messydates::make_messydate(`Date.of.Entry.into.Force`)) %>%
See comment above... In theory this is correct, but I will change message to include more information. Thank you.

2022-05-31 11:56 UTC, henriquesposito commented on data-raw/agreements/LABPTA/prepare-LABPTA.R
> +                        Force = messydates::make_messydate(as.character(year))) %>%
See above. Thank you.

2022-06-02 05:57 UTC, jhollway requested changes

2022-06-02 05:57 UTC, jhollway commented on .github/workflows/pushrelease.yml
>            prerelease: false
Check with @henriquesposito whether this is set up correctly

2022-06-02 05:57 UTC, jhollway commented on NEWS.md
> +  `manypkgs::code_memberships()`.
Is this maybe an ambiguous function name? I mean, does it code which countries are members?

2022-06-02 05:57 UTC, jhollway commented on NEWS.md
> +
I don't know where to put this, but why does `manytrade::references$DESTA_REF` seem to have lines with missing `manyID2` and empty `RefType`?

2022-06-02 05:57 UTC, jhollway commented on R/manytrade-agreements.R
> +#'  Memb.procedures, treatyID.}
It seems that the `Memb.*` variables code missing data as strings, e.g. `"NA"` rather than `NA` -- this needs to be handled in the preparation script

2022-06-02 05:57 UTC, jhollway commented on R/manytrade-texts.R
> +"texts"
Missing treaty texts should be `NA` not `"Not found"`? What do you think @henriquesposito ?

2022-06-02 05:57 UTC, jhollway commented on NEWS.md
> +  database.
Do they differ from those in `"TOTA"`? Are they more precise than those in other datasets?

2022-06-02 05:57 UTC, jhollway commented on NEWS.md
> +  * Closed #9 by incorporating TOTA database to the `AGR_TXT` dataset in the
Why is it called `AGR_`? Maybe also `GNEVAR_`?

2022-06-02 06:01 UTC, jhollway requested changes

2022-06-02 06:01 UTC, jhollway commented on .gitignore
> +*.DS_Store
Is this working to pick up all stray `.DS_Store` files? I've just deleted several more that were on the develop branch.

2022-06-02 08:31 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
>            prerelease: false
All the workflow actions are setup consistently across the package and encompass the new changes. However, we are still having issues with both PRchecks and pushrelease on the other packages that I am still looking into, so I might have to change these as well. I wonder if we could try and close this PR rather soon so that we can work on fixing the CI issues here, since this package is not on CRAN. What do you think @jhollway ?

2022-06-02 08:36 UTC, henriquesposito commented on R/manytrade-texts.R
> +"texts"
I agree, that sounds good! @jaeltan could we handle this in the preparation script and perhaps see how the `skimr` report returns these? Thank you.

2022-06-07 08:17 UTC, jaeltan commented on NEWS.md
> +  `manypkgs::code_memberships()`.
Since it codes the conditions and procedures for a state acceding to the treaty what about changing the name to code_accession? @jhollway @henriquesposito what do you think?

2022-06-07 21:30 UTC, jhollway commented on NEWS.md
> +  `manypkgs::code_memberships()`.
That sounds good, perhaps `code_accession_terms()`?

2022-06-08 07:24 UTC, henriquesposito commented on NEWS.md
> +  `manypkgs::code_memberships()`.
Sounds good, I will make the change in `{manypkags}`!

2022-06-08 07:42 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
>            prerelease: false
All are up to date!

2022-06-13 03:27 UTC, jhollway requested changes
Definitely getting there, @jaeltan. It's going to be super when it's ready to use.

2022-06-13 03:27 UTC, jhollway commented on DESCRIPTION
> +    manydata,
Move manydata to Depends

2022-06-13 03:27 UTC, jhollway commented on DESCRIPTION
>      dplyr,
Are these required imports, or only really via manydata?

2022-06-13 03:27 UTC, jhollway commented on NEWS.md
> +  `manypkgs::code_accession_terms()`.
Is this the only addition/new feature in GNEVAR? Do we have any better information on dates in GNEVAR?

2022-06-13 03:27 UTC, jhollway commented on NEWS.md
> +  `texts` database and added metadata to `TOTA` dataset in `agreements` database.
There seems like there is a lot of markup, e.g. `\n` still in many of these texts, as well as articles not separated and punctuation not respected. @henriquesposito are there ways to do better here soon, or do we need to inform users that (some of) these texts are not yet ready for use?

2022-06-13 03:27 UTC, jhollway commented on R/manytrade-agreements.R
> +#'  Memb.procedures, treatyID.}
The skimmr seems to be a fiddly dependency. Can we not just roll our own summary for the help pages?

2022-06-13 03:27 UTC, jhollway commented on R/manytrade-references.R
> +#' 3 variables: treatyID1, RefType, treatyID2.}
Should the order of these columns be `treatyID1, RefType, treatyID2` or `treatyID1, treatyID2, RefType` (across all packages)?

2022-06-13 03:27 UTC, jhollway commented on R/manytrade-texts.R
> +#'  trendID, labptaID, treatyID, destaID, TreatyText, url.}
Not sure if we need Beg, Signature, Force, etc -- just the ids to link back to manytrade::agreements?

2022-06-13 03:27 UTC, jhollway commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR$Memb.procedures <- gsub("NA", NA, GNEVAR$Memb.procedures)
These seem like long variable names. Maybe we can come up with standard names for these columns that are more succinct?

2022-06-13 03:27 UTC, jhollway commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +})
Don't we have a function for this now?

2022-06-13 03:27 UTC, jhollway commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +                -totaID, -gptadID, -destaID, -labptaID, -trendID)
This is fine, but a suggestion is to just minus a vector, e.g. `-c(dates, Sign.rev, TreatyText, ...)`

2022-06-13 03:27 UTC, jhollway commented on data-raw/memberships/DESTA_MEM/prepare-DESTA_MEM.R
>    dplyr::select(destaID, CountryID, Title, Beg, Signature, Force) %>%
Are we calling them countries or states?

2022-06-13 03:27 UTC, jhollway commented on data-raw/texts/GNEVAR_TXT/GNEVAR_TXT.bib
> +  author       = {Alschner, Wolfgang and Seiermann, Julia, and Skougarevskiy, Dmitriy},
Is there supposed to be a comma after `Julia`?

2022-06-13 07:10 UTC, henriquesposito commented on NEWS.md
> +  `texts` database and added metadata to `TOTA` dataset in `agreements` database.
Thank you for the comment, I see the issue. As I understand we keep the texts as they were when scraped. These can still be used to get different articles, accession, and termination. However, we could indeed create a standardise_texts() function in `{manypkgs}` that removes some of these markups and separates texts into articles. @jhollway would you like us to do so? @jaeltan what do you think? The only issue with this approach would be if we want to store storing these texts as lists of lists it would take lots of space, but we can try and play around with the formats as well. Thank you!

2022-06-13 07:25 UTC, jaeltan commented on R/manytrade-references.R
> +#' 3 variables: treatyID1, RefType, treatyID2.}
I will change this to be the same order as in manyenviron (`treatyID1, treatyID2, RefType`), when I was preparing the data I just thought it made sense for it to read across as `treatyID1` amends/cites/amended by/cited by `treatyID2`.

2022-06-13 07:33 UTC, jaeltan commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +})
The as_messydate function extracts and converts dates written in words to the standard YYYY-MM-DD format, but I added the part extracting the sentence where the date of signature is to make sure the date extracted is accurate, because some of the trade agreements contain multiple dates, and the first date in the text might not be the date of signature.

2022-06-13 07:52 UTC, jaeltan commented on R/manytrade-texts.R
> +#'  trendID, labptaID, treatyID, destaID, TreatyText, url.}
I would prefer to keep the `Beg, Signature, Force` variables because I use the GNEVAR_TXT dataset as the base for the GNEVAR dataset, and if I removed them I would have to add them back in later from other sources. I could remove the `totaID, gptadID` etc though.

2022-06-13 09:55 UTC, jaeltan commented on data-raw/memberships/DESTA_MEM/prepare-DESTA_MEM.R
>    dplyr::select(destaID, CountryID, Title, Beg, Signature, Force) %>%
I can change it to stateID and State Name etc, same for manyenviron, which is currently using 'CountryID' and 'SignatureCountry'.

2022-06-14 10:04 UTC, jaeltan commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR$Memb.procedures <- gsub("NA", NA, GNEVAR$Memb.procedures)
Maybe accessionC and accessionP? @jhollway

2022-06-27 12:30 UTC, jaeltan commented on NEWS.md
> +  `texts` database and added metadata to `TOTA` dataset in `agreements` database.
The texts are now pre-cleaned with the `standardise_texts` function which removes the `\n `spacing and also marks out Articles, Appendices, Annexes, and Protocols in capital letters.

2022-07-11 15:34 UTC, jhollway approved these changes
I haven't trawled through all the data, but further issues should reveal themselves with the next version of manydata and the visualisation functions

2022-07-11 15:34 UTC, jhollway commented on DESCRIPTION
> +Date: 2022-06-10
Update date

2022-07-11 15:34 UTC, jhollway commented on DESCRIPTION
> +    rlang,
Is this suggests really necessary?

2022-07-11 15:34 UTC, jhollway commented on DESCRIPTION
> +    messydates,
Are these necessary for this package? Or will the manydata dependency already cover this @henriquesposito ?

2022-07-12 08:24 UTC, henriquesposito commented on DESCRIPTION
> +    rlang,
For very few of these packages it is, I will clean these now.

2022-07-12 10:24 UTC, merged