Verified MetaData & Texts
globalgov/manytrade pull request #35
Opened 2023-02-23 08:33 UTC by AndersIHEID

# Description

Verified `Signature`, `Force`, `End`, `Parties`, `Url` in the HUGGO_verified.csv for 549 treaties. Also added 375 raw text treaties. Also added 135 formatted treaty texts.  

## Data

* Closed issue #34 by verifying MetaData(`Signature`, `Force`, `End`, `Parties`, `Url`) for trade agreements in HUGGO dataset.
* Added treaty texts for the agreements in HUGGO dataset.  

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Package builds on my OS without issues
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-02-28 10:50 UTC, jaeltan requested changes
Thank you for all the hard work and effort you have put into this package @AndersIHEID ! Just some modifications to the way code is written and some general documentation issues and we should be able to merge this.

2023-02-28 10:50 UTC, jaeltan commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, AgreementType, DocType, GeogArea, Signature, Force, treatyID, destaID.}
make sure the number of characters in each line doesn't exceed the lintr guidelines. You can see this when you run `lintr::lint_package()`

2023-02-28 10:50 UTC, jaeltan commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, Signature, Force, treatyID, TreatyText, url, End, Parties.}
Can we remove the HUGGOMetaData.csv file? Also, I think we can remove the TreatyText variable since we are not storing the texts in the database anymore, or we can change this variable to indicate if a treaty text is available for this agreement?

2023-02-28 10:50 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- cbind(HUGGO_verified, TreatyText = treaty_texts)
Do we still need the TreatyText column now that we are storing the texts as txt files?

2023-02-28 10:50 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +  mutate(Beg = coalesce(Signature, "N/A"))
can you add a `[package name]::` before the function name (eg. `dplyr::mutate()`) to call the package so that we don't have to use library(dplyr)

2023-02-28 10:50 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +names(HUGGO_verified)[10] <- "RowNumbers"
use `dplyr::rename()` to rename variable names instead of indexing manually

2023-02-28 10:50 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +names(merged_df)[1] <- "manyID"
Use `dplyr::rename()`

2023-02-28 10:50 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +         End = as_messydate(End))
Can you also reorder the variables using `dplyr::relocate()` so that the first few columns are manyID, Title, Beg, Signature, Force, End?

2023-03-01 14:57 UTC, AndersIHEID commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, Signature, Force, treatyID, TreatyText, url, End, Parties.}
Removing HUGGOMetaData.csv file is fine by me. I've left it for now but can remove anytime. TreatyText variable has been removed and replaced by TreatyTextStatus 0 = no text collected, 1 = text (raw or formatted) collected.

2023-03-01 14:57 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +names(HUGGO_verified)[10] <- "RowNumbers"
Done & pushed.

2023-03-01 14:57 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +names(merged_df)[1] <- "manyID"
Done & pushed.

2023-03-01 14:58 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +         End = as_messydate(End))
Done & pushed.

2023-03-02 08:29 UTC, jaeltan requested changes

2023-03-02 08:29 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- dplyr::select(HUGGO_verified, manyID,Title,Beg,Signature,Force,treatyID,url,End,Parties, HUGGOO_RowNumber)
Can you confirm that HUGGOO_RowNumber is spelled correctly and that HUGGO does not have an extra 'O'?

2023-03-02 08:29 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +merged_df <- dplyr::select(
Can you break down this code into separate steps using %>% so that it is clearer what you are doing?

2023-03-02 09:08 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- dplyr::select(HUGGO_verified, manyID,Title,Beg,Signature,Force,treatyID,url,End,Parties, HUGGOO_RowNumber)
In the HUGGO_verified.csv, the column is indeed called HUGGOO_RowNumber (with two 'O's). So the script is correct.

2023-03-02 09:15 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- dplyr::select(HUGGO_verified, manyID,Title,Beg,Signature,Force,treatyID,url,End,Parties, HUGGOO_RowNumber)
What is the extra 'O' for? If it is a spelling error can you remove it please

2023-03-02 09:45 UTC, henriquesposito reviewed
Thank you for all the hard work @AndersIHEID and @jaeltan! Using .txt and .csv files seems to work well to keep track of all changes idea to keep track of all this changes. Just a few more details and we should be ready to merge soon!

2023-03-02 09:45 UTC, henriquesposito commented on R/manytrade-agreements.R
> +#' 10 variables: manyID, Title, Beg, AgreementType, DocType, GeogArea, Signature, Force, treatyID, destaID.}
Please split documentation lines over 80 characters (border line). As Jael mention, the best way to catch these is to run ´lintr::lint_package()´.

2023-03-02 09:45 UTC, henriquesposito commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO <- merged_df
Practical question for the .rda file below: are we also going to overwrite the agreements database in the develop branch? 

To avoid issues, I would suggest we overwrite/add the HUGGO raw data in .csv/.txt but wait to 'export the data' into the agreements database once in the develop branch. If there were changes in any of the other datasets in the agreements database in the develop branch in the meantime these could be also overwritten, I am correct @jaeltan ?

2023-03-02 11:04 UTC, jaeltan requested changes

2023-03-02 11:04 UTC, jaeltan commented on NEWS.md
> +Data
You only need to copy-paste the part under the subheading ##Data. Also, the new entry should be pasted above the current version number and the new version number (# manytrade 0.2.1) added in the first line.

2023-03-02 11:05 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO <- merged_df
There were no changes made to the other datasets, so we should be fine to overwrite the agreements.rda file directly in this case. Thanks @henriquesposito for the reminder!

2023-03-02 11:17 UTC, jaeltan approved these changes

2023-03-02 11:17 UTC, merged