Improved HUGGO dataset with verified metadata and treaty texts
globalgov/manytrade pull request #36
Opened 2023-03-02 11:20 UTC by jaeltan

# Description

This minor release includes the addition of verified data and treaty texts for trade agreements.

## Data

* Closed #34 by verifying metadata (`Signature`, `Force`, `End`, `Parties`, `Url`) for trade agreements in HUGGO dataset.
* Added treaty texts for the agreements in HUGGO dataset.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-03-06 13:54 UTC, jhollway reviewed
An impressive amount of work @AndersIHEID. @jaeltan should be able to help make sure the preparation scripts and everything are as efficient and standard as possible. @henriquesposito, can you check whether the treaty texts, particularly the formatted versions, are sufficiently structured?

2023-03-06 13:54 UTC, jhollway commented on DESCRIPTION
>       c(person(given = "James",
Add Anders to the bottom?

2023-03-06 13:54 UTC, jhollway commented on NEWS.md
> +* Added treaty texts for the agreements in HUGGO dataset.
Can we summarise how much change there is in this version since the last here?

2023-03-06 13:54 UTC, jhollway commented on data-raw/agreements/HUGGO/HUGGO_verified.csv
> +1;GATT_1947O;GATT471947;30/10/1947;01/01/1948;https://www.wto.org/english/docs_e/legal_e/gatt47_e.pdf;NA;1;Australia, Belgium, Brazil, Burma, Canada, Ceylon, Chile, China, Cuba, Czechoslovakia, Franc
Dates seem to be in incorrect format (should be yyyy-mm-dd). Parties information should be in HUGGO_MEM.

2023-03-06 13:54 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +links <- readxl::read_excel("data-raw/agreements/HUGGO/links.xlsx")
Please store this as a csv so that it is easier to see line changes over time via git.

2023-03-06 13:54 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +         Parties = `10`)
`manypkgs::transmutate()` should help with all this.

2023-03-06 13:54 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO <- merged_df
Why not just assign last line to `HUGGO`?

2023-03-07 08:29 UTC, henriquesposito commented
Thank you for the great work @jaeltan and @AndersIHEID ! The texts format are good, much better already! Please let me know if you need help with anything. Thank you!

2023-03-07 10:15 UTC, jaeltan commented on NEWS.md
> -* Closed issue Check Signature and Force dates, and add End dates #34 by verifying MetaData(Signature, Force, End, Parties, Url) for trade agreements in HUGGO dataset.
You can remove the 'issue Check Signature ... End dates' only the issue number is needed here

2023-03-07 10:39 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/HUGGO_verified.csv
> +1;GATT_1947O;GATT471947;30/10/1947;01/01/1948;https://www.wto.org/english/docs_e/legal_e/gatt47_e.pdf;NA;1;Australia, Belgium, Brazil, Burma, Canada, Ceylon, Chile, China, Cuba, Czechoslovakia, Franc
Updated HUGGO_verified.csv to format yyyy/mm/dd for Date variables & removed Parties variable. Waiting with HUGGO_MEM changes

2023-03-07 15:54 UTC, jhollway requested changes

2023-03-07 15:54 UTC, jhollway commented on NEWS.md
> +* Added treaty texts for the agreements in HUGGO dataset.
This line should have the 510 (135 + 375) figure

2023-03-07 15:54 UTC, jhollway commented on data-raw/agreements/HUGGO/links.csv
> +﻿manyID;Title;Beg;Signature;Force;destaID;labptaID;trendID;treatyID;url;alt.url;Remarks;Language
Does it matter that these are semi-colon separated instead of comma separated @henriquesposito ?

2023-03-07 15:54 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- read.csv2(file.choose())
Replace file.choose() with actual (relative if necessary) reference

2023-03-07 15:54 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_verified <- dplyr::mutate(HUGGO_verified, Beg = dplyr::coalesce(Signature, "N/A"))
`"N/A"` should be `NA_char` or equivalent

2023-03-08 08:31 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/links.csv
> +﻿manyID;Title;Beg;Signature;Force;destaID;labptaID;trendID;treatyID;url;alt.url;Remarks;Language
Not a problem to change the delimiter to "," (comma). @henriquesposito 

";" (semi-colon) was used as there are commas within the .csv file (url column) which I have read can cause data issues if the delimiter is also ","

To use "," (comma) as the delimiter, we will have to enclose the url column in quotes (e.g. "www.facebook.com/123,876") to preserve "," (commas) within the links. 

Let me know if that is okay.

2023-03-08 08:53 UTC, henriquesposito commented on data-raw/agreements/HUGGO/links.csv
> +﻿manyID;Title;Beg;Signature;Force;destaID;labptaID;trendID;treatyID;url;alt.url;Remarks;Language
Great! Yes, is it ok enclose the url column. Please change it to commas to make it easier for users. Thank you very much @AndersIHEID

2023-03-08 10:39 UTC, AndersIHEID commented on data-raw/agreements/HUGGO/HUGGO_verified.csv
> +1;GATT_1947O;GATT471947;30/10/1947;01/01/1948;https://www.wto.org/english/docs_e/legal_e/gatt47_e.pdf;NA;1;Australia, Belgium, Brazil, Burma, Canada, Ceylon, Chile, China, Cuba, Czechoslovakia, Franc
Removed Parties variable from HUGGO in agreements.rda

2023-03-21 11:52 UTC, henriquesposito approved these changes
Thank you for the great work @jaeltan and @AndersIHEID ! Please just make sure you adress the last few more minor changes requested and that the `{pkgdown}` website builds without warnings to avoid any issues later on with the merge.

2023-03-21 11:52 UTC, henriquesposito commented on .github/workflows/prchecks.yml
> +      - master
In manyenviron, we now run the tests/checks on the workflow files on "ubuntu-latest" instead of "ubuntu-20.04". I don't think we will have any issues here, just FYI in case you want to change.

2023-03-21 11:52 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> +      - master
Remove master

2023-03-21 11:52 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> +      - master
As well, in manyenviron we run the tests/checks on the workflow files on "ubuntu-latest", just FYI in case you want to change.

2023-03-21 11:52 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> -          DEFAULT_BUMP: minor
If this is a minor bump, you can re-add this line just in case

2023-03-21 11:52 UTC, henriquesposito commented on NEWS.md
> +* Metadata (`Signature`, `Force`, `End`, `Parties`, `url`) confirmed for 549 agreements
In HUGGO? Maybe add where here

2023-03-21 11:52 UTC, henriquesposito commented on data-raw/agreements/HUGGO/HUGGO.bib
> +  url = {https://edit.wti.org/app.php/document/investment-treaty/search}
Add line at the end

2023-03-22 09:45 UTC, merged